name = "money-tsvetik-bot-2"
main = "worker.js"
compatibility_date = "2026-05-27"

[observability]
enabled = true

[observability.logs]
invocation_logs = true

[[kv_namespaces]]
binding = "KV"
id = "056a2e87fb4045cc872139f8ead67058"
